# Schema ID for credential storage (you can use any UUIDv4)
schema_id = "a7b3c1a2-5f3e-4c8b-9b1e-1c3e4f5a6b7c"

# Your org did
org_secret_key = "YOUR_ORG_SECRET_KEY"

# Your org did
org_did = "YOUR_ORG_DID"

# Node configuration
[node_a]
url= "https://nildb-zy8u.nillion.network"
jwt= "YOUR_JWT_A"

[node_b]
url= "https://nildb-rl5g.nillion.network"
jwt="YOUR_JWT_B"

[node_c]
url= "https://nildb-lpjp.nillion.network"
jwt="YOUR_JWT_C"



