# Schema ID for credential storage (you can use any UUIDv4)
schema_id = "97b00aeb-ac5c-43a3-8704-dc7df992fb85"

# Your org did
org_secret_key = "YOUR_SECRET_KEY"

# Your org did
org_did = "YOUR_DID"

# Node configuration
[node_a]
url= "https://nildb-zy8u.nillion.network"
did= "did:nil:testnet:nillion1fnhettvcrsfu8zkd5zms4d820l0ct226c3zy8u"
jwt= "YOUR_JWT_A"

[node_b]
url= "https://nildb-rl5g.nillion.network"
did= "did:nil:testnet:nillion14x47xx85de0rg9dqunsdxg8jh82nvkax3jrl5g"
jwt= "YOUR_JWT_B"

[node_c]
url= "https://nildb-lpjp.nillion.network"
did= "did:nil:testnet:nillion167pglv9k7m4gj05rwj520a46tulkff332vlpjp"
jwt= "YOUR_JWT_C"



