# Schema ID for credential storage (you can use any UUIDv4)
schema_id = "6b9e06c2-df0d-4535-83ae-7af792df5fa8"

# Your org did
org_secret_key = "a70eb679826e742ddccb8ababfec9ed2014c9e07de5396af1627854bc46a42f8"

# Your org did
org_did = "did:nil:testnet:nillion189n0gr8z203w60l4fhqa9elgy2ecyhles7u9z7"

# Node configuration
[node_a]
url= "https://nildb-zy8u.nillion.network"
did= "did:nil:testnet:nillion1fnhettvcrsfu8zkd5zms4d820l0ct226c3zy8u"

[node_b]
url= "https://nildb-rl5g.nillion.network"
did= "did:nil:testnet:nillion14x47xx85de0rg9dqunsdxg8jh82nvkax3jrl5g"

[node_c]
url= "https://nildb-lpjp.nillion.network"
did= "did:nil:testnet:nillion167pglv9k7m4gj05rwj520a46tulkff332vlpjp"



